Merged online-docs into master
wunderio/silta pull request #34
Opened 2021-02-12 11:14 UTC by DavisAre

Docs are ready, search added. Makes sense to merge into master.

2021-02-12 11:25 UTC, tharna requested changes

2021-02-12 11:25 UTC, tharna commented on .github/workflows/documentation.yml
> +    branches: [feature/master]
this should be just master to make things work after merging.

2021-02-12 11:28 UTC, DavisAre commented on .github/workflows/documentation.yml
> +    branches: [feature/master]
Sorry, my bad. Fixed.

2021-02-12 11:34 UTC, tharna approved these changes
Looks great!

2021-02-15 10:12 UTC, DavisAre commented
FYI - @agnis-mateuss @Jancis: 
@tharna has reviewed the changes. Please consider a merge when possible.

2021-02-16 08:06 UTC, agnis-mateuss approved these changes

2021-02-16 09:27 UTC, merged